# Generated by Django 2.1 on 2018-08-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='university.Person')),
                ('photo', models.ImageField(upload_to='image_photo')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('employment', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.FloatField()),
            ],
            bases=('university.person', models.Model),
        ),
    ]
